### PR TITLE
Disable no-continue rule

### PR DESCRIPTION
**Pull request by tavurth**
```
while (iAmStillProcessing) {
  if (iShouldSkipThisLoop) {
    continue;
  }
}
```
Currently throws an error.

### CODE REVIEW

**Review by vandyw95 — COMMENTED** [review]
Can you please add an example of what case it is a must?

**Comment by tavurth** [comment]
@vandyw95 Added

**Review by vandyw95 — APPROVED** [review]
Go on

**Review by vandyw95 — APPROVED** [review]

**Review by beermindnor — APPROVED** [review]

**Review by beermindnor — APPROVED** [review]

**Comment by JustBeard** [comment]
https://github.com/airbnb/javascript/issues/1103

**Comment by tavurth** [comment]
I would agree about the thing with loops. 
However airbnb already warns us when using loops, and won't let us do so without explicitly stating to disable for the next line.

Why should we disable for two lines inside a loop, as it just makes the code more cluttered

**Comment by JustBeard** [comment]
Agree. Scheduled a meeting to discuss this and other few PRs what are stuck here.

**Comment by JustBeard** [comment]
Will be included as part of 2.0.0

**Pull request closed without merging**
